In [1]:
import pandas as pd
df = pd.read_csv("../data/raw/Dataset.csv")
df.shape

(8790, 10)

In [2]:
df.head()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8790 non-null   str
 1   type          8790 non-null   str
 2   title         8790 non-null   str
 3   director      8790 non-null   str
 4   country       8790 non-null   str
 5   date_added    8790 non-null   str
 6   release_year  8790 non-null   int64
 7   rating        8790 non-null   str
 8   duration      8790 non-null   str
 9   listed_in     8790 non-null   str
dtypes: int64(1), str(9)
memory usage: 1.6 MB

In [4]:
df.isna().sum()

show_id         0
type            0
title           0
director        0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
dtype: int64

In [5]:
(df == "Not Given").sum()

show_id            0
type               0
title              0
director        2588
country          287
date_added         0
release_year       0
rating             0
duration           0
listed_in          0
dtype: int64

In [6]:
df["director"].value_counts().head(5)

director
Not Given                 2588
Rajiv Chilaka               20
Raúl Campos, Jan Suter      18
Alastair Fothergill         18
Suhas Kadav                 16
Name: count, dtype: int64

In [7]:
df[df["director"] != "Unknown"]["director"].value_counts().head(5)

director
Not Given                 2588
Rajiv Chilaka               20
Raúl Campos, Jan Suter      18
Alastair Fothergill         18
Suhas Kadav                 16
Name: count, dtype: int64

In [8]:
df_clean = df.copy()

In [9]:
df_clean["director"] = df_clean["director"].replace("Not Given", "Unknown")
df_clean["country"] = df_clean["country"].replace("Not Given", "Unknown")

In [10]:
print((df_clean == "Not Given").sum().sum())
print((df_clean["director"] == "Unknown").sum())
print((df_clean["country"] == "Unknown").sum())
print((df == "Not Given").sum().sum())

0
2588
287
2875

In [11]:
print(df_clean.duplicated().sum())
print(df_clean["show_id"].duplicated().sum())
print(df_clean["title"].duplicated().sum())

0
0
3

In [12]:
dup_titles = df_clean[df_clean["title"].duplicated(keep=False)].sort_values("title")
dup_titles

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
2925,s3963,Movie,15-Aug,Swapnaneel Jayakar,India,3/29/2019,2019,TV-14,124 min,"Comedies, Dramas, Independent Movies"
4261,s5967,Movie,15-Aug,Swapnaneel Jayakar,India,3/29/2019,2019,TV-14,124 min,"Comedies, Dramas, Independent Movies"
3285,s4523,Movie,22-Jul,Paul Greengrass,Norway,10/10/2018,2018,R,144 min,"Dramas, Thrillers"
4260,s5966,Movie,22-Jul,Paul Greengrass,Norway,10/10/2018,2018,R,144 min,"Dramas, Thrillers"
393,s3997,TV Show,9-Feb,Unknown,Pakistan,3/20/2019,2018,TV-14,1 Season,"International TV Shows, TV Dramas"
537,s5965,TV Show,9-Feb,Unknown,Pakistan,3/20/2019,2018,TV-14,1 Season,"International TV Shows, TV Dramas"

In [13]:
df_clean.drop(columns="show_id").duplicated().sum()

np.int64(3)

In [14]:
dup_titles[["show_id", "title", "duration", "listed_in"]]

     show_id   title  duration                             listed_in
2925   s3963  15-Aug   124 min  Comedies, Dramas, Independent Movies
4261   s5967  15-Aug   124 min  Comedies, Dramas, Independent Movies
3285   s4523  22-Jul   144 min                     Dramas, Thrillers
4260   s5966  22-Jul   144 min                     Dramas, Thrillers
393    s3997   9-Feb  1 Season     International TV Shows, TV Dramas
537    s5965   9-Feb  1 Season     International TV Shows, TV Dramas

In [16]:
cols_to_compare = df_clean.columns.drop("show_id")
removed_duplicates = df_clean[df_clean.duplicated(subset=cols_to_compare, keep="first")]

In [17]:
df_clean = df_clean.drop_duplicates(subset=cols_to_compare, keep="first").reset_index(drop=True)

In [18]:
print(df_clean.shape)
print(df_clean.drop(columns="show_id").duplicated().sum())
print(df_clean["show_id"].is_unique)
removed_duplicates[["show_id", "title"]]

(8787, 10)
0
True

     show_id   title
537    s5965   9-Feb
4260   s5966  22-Jul
4261   s5967  15-Aug