In [1]:
import pandas as pd
df = pd.read_csv("../data/raw/Dataset.csv")
df.shape

(8790, 10)

In [2]:
df.head()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8790 non-null   str
 1   type          8790 non-null   str
 2   title         8790 non-null   str
 3   director      8790 non-null   str
 4   country       8790 non-null   str
 5   date_added    8790 non-null   str
 6   release_year  8790 non-null   int64
 7   rating        8790 non-null   str
 8   duration      8790 non-null   str
 9   listed_in     8790 non-null   str
dtypes: int64(1), str(9)
memory usage: 1.6 MB

In [4]:
df.isna().sum()

show_id         0
type            0
title           0
director        0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
dtype: int64

In [5]:
(df == "Not Given").sum()

show_id            0
type               0
title              0
director        2588
country          287
date_added         0
release_year       0
rating             0
duration           0
listed_in          0
dtype: int64

In [6]:
df["director"].value_counts().head(5)

director
Not Given                 2588
Rajiv Chilaka               20
Raúl Campos, Jan Suter      18
Alastair Fothergill         18
Suhas Kadav                 16
Name: count, dtype: int64

In [7]:
df[df["director"] != "Unknown"]["director"].value_counts().head(5)

director
Not Given                 2588
Rajiv Chilaka               20
Raúl Campos, Jan Suter      18
Alastair Fothergill         18
Suhas Kadav                 16
Name: count, dtype: int64

In [8]:
df_clean = df.copy()

In [9]:
df_clean["director"] = df_clean["director"].replace("Not Given", "Unknown")
df_clean["country"] = df_clean["country"].replace("Not Given", "Unknown")

In [10]:
print((df_clean == "Not Given").sum().sum())
print((df_clean["director"] == "Unknown").sum())
print((df_clean["country"] == "Unknown").sum())
print((df == "Not Given").sum().sum())

0
2588
287
2875

In [11]:
print(df_clean.duplicated().sum())
print(df_clean["show_id"].duplicated().sum())
print(df_clean["title"].duplicated().sum())

0
0
3

In [12]:
dup_titles = df_clean[df_clean["title"].duplicated(keep=False)].sort_values("title")
dup_titles

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
2925,s3963,Movie,15-Aug,Swapnaneel Jayakar,India,3/29/2019,2019,TV-14,124 min,"Comedies, Dramas, Independent Movies"
4261,s5967,Movie,15-Aug,Swapnaneel Jayakar,India,3/29/2019,2019,TV-14,124 min,"Comedies, Dramas, Independent Movies"
3285,s4523,Movie,22-Jul,Paul Greengrass,Norway,10/10/2018,2018,R,144 min,"Dramas, Thrillers"
4260,s5966,Movie,22-Jul,Paul Greengrass,Norway,10/10/2018,2018,R,144 min,"Dramas, Thrillers"
393,s3997,TV Show,9-Feb,Unknown,Pakistan,3/20/2019,2018,TV-14,1 Season,"International TV Shows, TV Dramas"
537,s5965,TV Show,9-Feb,Unknown,Pakistan,3/20/2019,2018,TV-14,1 Season,"International TV Shows, TV Dramas"

In [13]:
df_clean.drop(columns="show_id").duplicated().sum()

np.int64(3)

In [14]:
dup_titles[["show_id", "title", "duration", "listed_in"]]

     show_id   title  duration                             listed_in
2925   s3963  15-Aug   124 min  Comedies, Dramas, Independent Movies
4261   s5967  15-Aug   124 min  Comedies, Dramas, Independent Movies
3285   s4523  22-Jul   144 min                     Dramas, Thrillers
4260   s5966  22-Jul   144 min                     Dramas, Thrillers
393    s3997   9-Feb  1 Season     International TV Shows, TV Dramas
537    s5965   9-Feb  1 Season     International TV Shows, TV Dramas

In [15]:
cols_to_compare = df_clean.columns.drop("show_id")
removed_duplicates = df_clean[df_clean.duplicated(subset=cols_to_compare, keep="first")]

In [16]:
df_clean = df_clean.drop_duplicates(subset=cols_to_compare, keep="first").reset_index(drop=True)

In [17]:
print(df_clean.shape)
print(df_clean.drop(columns="show_id").duplicated().sum())
print(df_clean["show_id"].is_unique)
removed_duplicates[["show_id", "title"]]

(8787, 10)
0
True

     show_id   title
537    s5965   9-Feb
4260   s5966  22-Jul
4261   s5967  15-Aug

In [18]:
date_pattern = r"^\d{1,2}-[A-Za-z]{3}$|^[A-Za-z]{3}-\d{1,2}$"
date_like = df_clean[df_clean["title"].str.match(date_pattern)]
print(len(date_like))

5

In [19]:
date_like[["show_id", "title", "type", "release_year", "director"]]

     show_id   title     type  release_year            director
393    s3997   9-Feb  TV Show          2018             Unknown
2924   s3963  15-Aug    Movie          2019  Swapnaneel Jayakar
3284   s4523  22-Jul    Movie          2018     Paul Greengrass
3743   s5199  SPF-18    Movie          2017         Alex Israel
4258   s5964   1-Oct    Movie          2014      Kunle Afolayan

### Decision: possibly auto-converted titles
Found 5 titles matching a date-like pattern: 9-Feb, 15-Aug, 22-Jul, SPF-18, 1-Oct.
SPF-18 looks like a genuine title (false positive). The other 4 were probably
converted from names such as "22 July" by spreadsheet software. The original
names cannot be recovered from the file alone, so titles were left unchanged and
the issue is documented as a limitation. Impact: 4 of 8,787 rows (about 0.05%).

In [20]:
print(df_clean.shape)
print(df_clean["title"].isin(["9-Feb", "15-Aug", "22-Jul", "SPF-18", "1-Oct"]).sum())

(8787, 10)
5

In [21]:
df_clean["date_added"].str.match(r"^\d{1,2}/\d{1,2}/\d{4}$").value_counts()

date_added
True    8787
Name: count, dtype: int64

In [22]:
parts = df_clean["date_added"].str.split("/", expand=True).astype(int)
print(parts[0].max(), parts[1].max())

12 31

In [23]:
df_clean["duration"].str.split(" ").str[1].value_counts()
pd.crosstab(df_clean["type"], df_clean["duration"].str.split(" ").str[1])

duration  Season  Seasons   min
type
Movie          0        0  6124
TV Show     1790      873     0

In [24]:
df_clean["date_added"] = pd.to_datetime(df_clean["date_added"], format="%m/%d/%Y")

In [25]:
df_clean["duration_value"] = df_clean["duration"].str.split(" ").str[0].astype(int)
df_clean["duration_unit"] = df_clean["duration"].str.split(" ").str[1].replace("Seasons", "Season")

In [26]:
print(df_clean[["date_added", "duration_value"]].dtypes)
print(df_clean["date_added"].min(), df_clean["date_added"].max())
print(df_clean.groupby("duration_unit")["duration_value"].agg(["count", "min", "max"]))
print(df_clean.shape)

date_added        datetime64[us]
duration_value             int64
dtype: object
2008-01-01 00:00:00 2021-09-25 00:00:00
               count  min  max
duration_unit
Season          2663    1   17
min             6124    3  312
(8787, 12)

In [27]:
year_added = df_clean["date_added"].dt.year
early = df_clean[year_added < df_clean["release_year"]]
print(len(early))
print((year_added - df_clean["release_year"]).describe())
early[["title", "type", "release_year", "date_added"]].head(10)

14
count    8787.000000
mean        4.691931
std         8.791157
min        -3.000000
25%         0.000000
50%         1.000000
75%         5.000000
max        93.000000
dtype: float64

                           title     type  release_year date_added
3868  Hans Teeuwen: Real Rancour    Movie          2018 2017-07-01
5135                    Incoming    Movie          2019 2018-10-26
5175                 Jack Taylor  TV Show          2016 2013-03-31
6945                       Hilda  TV Show          2021 2020-12-14
6989                Polly Pocket  TV Show          2021 2020-11-15
7352               Love Is Blind  TV Show          2021 2020-02-13
7433                Fuller House  TV Show          2020 2019-12-06
7481          Maradona in Mexico  TV Show          2020 2019-11-13
7514             BoJack Horseman  TV Show          2020 2019-10-25
7534            The Hook Up Plan  TV Show          2020 2019-10-11

In [28]:
print(early["type"].value_counts())
early[["show_id", "title", "type", "release_year", "date_added"]]

type
TV Show    12
Movie       2
Name: count, dtype: int64

     show_id                       title     type  release_year date_added
3868   s5395  Hans Teeuwen: Real Rancour    Movie          2018 2017-07-01
5135   s7064                    Incoming    Movie          2019 2018-10-26
5175   s7113                 Jack Taylor  TV Show          2016 2013-03-31
6945   s1552                       Hilda  TV Show          2021 2020-12-14
6989   s1697                Polly Pocket  TV Show          2021 2020-11-15
7352   s2921               Love Is Blind  TV Show          2021 2020-02-13
7433   s3169                Fuller House  TV Show          2020 2019-12-06
7481   s3288          Maradona in Mexico  TV Show          2020 2019-11-13
7514   s3370             BoJack Horseman  TV Show          2020 2019-10-25
7534   s3434            The Hook Up Plan  TV Show          2020 2019-10-11
7993   s4845   Unbreakable Kimmy Schmidt  TV Show          2019 2018-05-30
7994   s4846        Arrested Development  TV Show          2019 2018-05-29
8220   s5659                      Sense8  TV Show          2018 2016-12-23
8232   s5678                 Tokyo Trial  TV Show          2017 2016-12-13

In [29]:
df_clean["added_before_release"] = year_added < df_clean["release_year"]
print(df_clean["added_before_release"].sum())
print(df_clean.shape)

14
(8787, 13)

In [30]:
text_cols = ["show_id", "type", "title", "director", "country", "rating", "listed_in", "duration_unit"]

for col in text_cols:
    spaces = (df_clean[col] != df_clean[col].str.strip()).sum()
    case_variants = df_clean[col].nunique() - df_clean[col].str.lower().nunique()
    print(col, "| padded with spaces:", spaces, "| case variants:", case_variants)

df_clean["rating"].value_counts()

show_id | padded with spaces: 0 | case variants: 0
type | padded with spaces: 0 | case variants: 0
title | padded with spaces: 1 | case variants: 5
director | padded with spaces: 0 | case variants: 2
country | padded with spaces: 0 | case variants: 0
rating | padded with spaces: 0 | case variants: 0
listed_in | padded with spaces: 0 | case variants: 0
duration_unit | padded with spaces: 0 | case variants: 0

rating
TV-MA       3205
TV-14       2155
TV-PG        861
R            798
PG-13        490
TV-Y7        333
TV-Y         306
PG           287
TV-G         220
NR            79
G             41
TV-Y7-FV       6
NC-17          3
UR             3
Name: count, dtype: int64

In [31]:
df_clean.loc[df_clean["title"] != df_clean["title"].str.strip(), ["show_id", "title"]].map(repr)

      show_id               title
4715  's6530'  'Consequences\xa0'

In [32]:
def case_clashes(col):
    lower = df_clean[col].str.lower()
    forms = df_clean.groupby(lower)[col].transform("nunique")
    return df_clean[forms > 1].sort_values(col, key=lambda s: s.str.lower())

case_clashes("title")[["show_id", "title", "type", "release_year", "director"]]

     show_id                     title     type  release_year         director
3818   s5319                Death Note    Movie          2017     Adam Wingard
8257   s5752                DEATH NOTE  TV Show          2006          Unknown
415     s304      Esperando la carroza    Movie          1985  Alejandro Doria
4853   s6706      Esperando La Carroza    Movie          1985  Alejandro Doria
3636   s5034       FullMetal Alchemist    Movie          2017    Fumihiko Sori
8058   s5096       Fullmetal Alchemist  TV Show          2003          Unknown
220     s160            Love in a Puff    Movie          2010   Pang Ho-cheung
5358   s7346            Love In A Puff    Movie          2010   Pang Ho-cheung
6851   s1271  Sin senos sí hay paraíso  TV Show          2018          Unknown
8664   s8023  Sin Senos sí Hay Paraíso  TV Show          2018          Unknown

In [33]:
case_clashes("director")[["show_id", "title", "director"]]

     show_id                                 title                    director
2000   s2468                    I'm No Longer Here  Fernando Frías de la Parra
5754   s7867                                Rezeta  Fernando Frías De La Parra
977     s948                         State of Play             Kevin Macdonald
3011   s4096                             Black Sea             Kevin MacDonald
4119   s5755  Sky Ladder: The Art of Cai Guo-Qiang             Kevin MacDonald

In [34]:
df_clean["rating"].value_counts().tail(4)

rating
G           41
TV-Y7-FV     6
NC-17        3
UR           3
Name: count, dtype: int64

In [35]:
tmp = df_clean.assign(title_key=df_clean["title"].str.lower().str.strip())
key_cols = ["title_key", "type", "director", "country", "date_added",
            "release_year", "rating", "duration", "listed_in"]
near_dups = tmp[tmp.duplicated(subset=key_cols, keep=False)].sort_values("title_key")
near_dups[["show_id", "title", "date_added", "duration", "listed_in"]]

,show_id,title,date_added,duration,listed_in
2589,s3372,Consequences,2019-10-25,106 min,"Dramas, International Movies, Thrillers"
4715,s6530,Consequences,2019-10-25,106 min,"Dramas, International Movies, Thrillers"

In [36]:
director_fix = {
    "Fernando Frías De La Parra": "Fernando Frías de la Parra",
    "Kevin MacDonald": "Kevin Macdonald",
}
df_clean["director"] = df_clean["director"].replace(director_fix)
df_clean["rating"] = df_clean["rating"].replace({"UR": "NR"})
df_clean["title"] = df_clean["title"].str.strip()

In [37]:
print((df_clean["rating"] == "NR").sum())
print(df_clean["rating"].nunique())
print(len(case_clashes("director")))
print((df_clean["title"] != df_clean["title"].str.strip()).sum())
print(df_clean.shape)

82
13
0
0
(8787, 13)

In [38]:
pairs = ["love in a puff", "esperando la carroza", "sin senos sí hay paraíso"]
for t in pairs:
    rows = df_clean[df_clean["title"].str.lower() == t]
    differing = [c for c in rows.columns if c not in ("show_id", "title") and rows[c].nunique() > 1]
    print(t, "->", differing)

love in a puff -> ['date_added']
esperando la carroza -> ['date_added', 'rating']
sin senos sí hay paraíso -> ['date_added']

In [39]:
cols_to_compare = [c for c in df_clean.columns if c != "show_id"]
new_dups = df_clean[df_clean.duplicated(subset=cols_to_compare, keep="first")]
print(new_dups[["show_id", "title"]])
removed_duplicates = pd.concat([removed_duplicates, new_dups])
df_clean = df_clean.drop_duplicates(subset=cols_to_compare, keep="first").reset_index(drop=True)

     show_id         title
4715   s6530  Consequences

In [40]:
print(df_clean.shape)
print(df_clean["show_id"].is_unique)
print(df_clean.duplicated(subset=cols_to_compare).sum())
print(len(removed_duplicates))

(8786, 13)
True
0
4

In [41]:
pair_rows = df_clean[df_clean["title"].str.lower().isin(pairs)]
pair_rows.sort_values("title", key=lambda s: s.str.lower())[["show_id", "title", "date_added", "rating", "release_year"]]

     show_id                     title date_added rating  release_year
415     s304      Esperando la carroza 2021-08-05  TV-MA          1985
4852   s6706      Esperando La Carroza 2018-07-15     NR          1985
220     s160            Love in a Puff 2021-09-01  TV-MA          2010
5357   s7346            Love In A Puff 2018-08-01  TV-MA          2010
6850   s1271  Sin senos sí hay paraíso 2021-02-25  TV-MA          2018
8663   s8023  Sin Senos sí Hay Paraíso 2019-01-11  TV-MA          2018

### Decision: near-duplicate titles
Three titles (Love in a Puff, Esperando la carroza, Sin senos sí hay paraíso)
appear twice with the same title, director, country, year, duration and genres,
but different date_added (and a different rating for one). They are not exact
duplicates and the cause cannot be determined from the file, so all six rows
were kept. Maximum effect: 3 of 8,786 titles (about 0.03%).
One exact duplicate (Consequences, s6530) was removed after trimming a stray
space, which made it identical to s3372.

In [42]:
df_clean["main_country"] = df_clean["country"].str.split(",").str[0].str.strip()
df_clean["n_countries"] = df_clean["country"].str.split(",").str.len()
df_clean["main_genre"] = df_clean["listed_in"].str.split(",").str[0].str.strip()
df_clean["n_genres"] = df_clean["listed_in"].str.split(",").str.len()
df_clean["year_added"] = df_clean["date_added"].dt.year
df_clean["month_added"] = df_clean["date_added"].dt.month_name()

In [43]:
print((df_clean[["main_country", "main_genre"]] == "").sum())
print(df_clean["n_countries"].value_counts().sort_index())
print(df_clean["main_country"].value_counts().head(5))
print(df_clean.shape)
df_clean[["country", "main_country", "n_countries"]].sample(5, random_state=1)

main_country    0
main_genre      0
dtype: int64
n_countries
1    8786
Name: count, dtype: int64
main_country
United States     3240
India             1056
United Kingdom     638
Pakistan           420
Unknown            287
Name: count, dtype: int64
(8786, 19)

            country   main_country  n_countries
1160  United States  United States            1
1532  United States  United States            1
7231  United States  United States            1
8260         Taiwan         Taiwan            1
5061  United States  United States            1

In [44]:
df_clean = df_clean.drop(columns=["main_country", "n_countries"])
print(df_clean.shape)
print(df_clean["n_genres"].value_counts().sort_index())
df_clean[["listed_in", "main_genre", "n_genres"]].sample(5, random_state=1)

(8786, 17)
n_genres
1    2012
2    3050
3    3724
Name: count, dtype: int64

,listed_in,main_genre,n_genres
1160,"Children & Family Movies, Dramas",Children & Family Movies,2
1532,"Dramas, Independent Movies, Thrillers",Dramas,3
7231,TV Dramas,TV Dramas,1
8260,"International TV Shows, Romantic TV Shows, TV ...",International TV Shows,3
5061,"Comedies, Romantic Movies",Comedies,2

In [45]:
print(df_clean.isna().sum().sum())
print(df_clean["show_id"].is_unique)
print(df_clean.duplicated(subset=cols_to_compare).sum())
df_clean.info()

0
True
0
<class 'pandas.DataFrame'>
RangeIndex: 8786 entries, 0 to 8785
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   show_id               8786 non-null   str
 1   type                  8786 non-null   str
 2   title                 8786 non-null   str
 3   director              8786 non-null   str
 4   country               8786 non-null   str
 5   date_added            8786 non-null   datetime64[us]
 6   release_year          8786 non-null   int64
 7   rating                8786 non-null   str
 8   duration              8786 non-null   str
 9   listed_in             8786 non-null   str
 10  duration_value        8786 non-null   int64
 11  duration_unit         8786 non-null   object
 12  added_before_release  8786 non-null   bool
 13  main_genre            8786 non-null   object
 14  n_genres              8786 non-null   int64
 15  year_added            8786 non-null   int32
 16  month_added           8786 non-null   str
dtypes: bool(1), datetime64[us](1), int32(1), int64(3), object(2), str(9)
memory usage: 1.9+ MB

In [46]:
df_clean.to_csv("../data/processed/netflix_clean.csv", index=False)
removed_duplicates.to_csv("../data/processed/removed_duplicates.csv", index=False)
check = pd.read_csv("../data/processed/netflix_clean.csv", parse_dates=["date_added"])
print(check.shape, check["date_added"].dtype)

(8786, 17) datetime64[us]