In [1]:
import pandas as pd
df = pd.read_csv("../data/raw/Dataset.csv")
df.shape

(8790, 10)

In [2]:
df.head()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8790 non-null   str
 1   type          8790 non-null   str
 2   title         8790 non-null   str
 3   director      8790 non-null   str
 4   country       8790 non-null   str
 5   date_added    8790 non-null   str
 6   release_year  8790 non-null   int64
 7   rating        8790 non-null   str
 8   duration      8790 non-null   str
 9   listed_in     8790 non-null   str
dtypes: int64(1), str(9)
memory usage: 1.6 MB

In [4]:
df.isna().sum()

show_id         0
type            0
title           0
director        0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
dtype: int64

In [5]:
(df == "Not Given").sum()

show_id            0
type               0
title              0
director        2588
country          287
date_added         0
release_year       0
rating             0
duration           0
listed_in          0
dtype: int64

In [6]:
df["director"].value_counts().head(5)

director
Not Given                 2588
Rajiv Chilaka               20
Raúl Campos, Jan Suter      18
Alastair Fothergill         18
Suhas Kadav                 16
Name: count, dtype: int64

In [7]:
df[df["director"] != "Unknown"]["director"].value_counts().head(5)

director
Not Given                 2588
Rajiv Chilaka               20
Raúl Campos, Jan Suter      18
Alastair Fothergill         18
Suhas Kadav                 16
Name: count, dtype: int64

In [8]:
df_clean = df.copy()

In [9]:
df_clean["director"] = df_clean["director"].replace("Not Given", "Unknown")
df_clean["country"] = df_clean["country"].replace("Not Given", "Unknown")

In [10]:
print((df_clean == "Not Given").sum().sum())
print((df_clean["director"] == "Unknown").sum())
print((df_clean["country"] == "Unknown").sum())
print((df == "Not Given").sum().sum())

0
2588
287
2875

In [11]:
print(df_clean.duplicated().sum())
print(df_clean["show_id"].duplicated().sum())
print(df_clean["title"].duplicated().sum())

0
0
3

In [12]:
dup_titles = df_clean[df_clean["title"].duplicated(keep=False)].sort_values("title")
dup_titles

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
2925,s3963,Movie,15-Aug,Swapnaneel Jayakar,India,3/29/2019,2019,TV-14,124 min,"Comedies, Dramas, Independent Movies"
4261,s5967,Movie,15-Aug,Swapnaneel Jayakar,India,3/29/2019,2019,TV-14,124 min,"Comedies, Dramas, Independent Movies"
3285,s4523,Movie,22-Jul,Paul Greengrass,Norway,10/10/2018,2018,R,144 min,"Dramas, Thrillers"
4260,s5966,Movie,22-Jul,Paul Greengrass,Norway,10/10/2018,2018,R,144 min,"Dramas, Thrillers"
393,s3997,TV Show,9-Feb,Unknown,Pakistan,3/20/2019,2018,TV-14,1 Season,"International TV Shows, TV Dramas"
537,s5965,TV Show,9-Feb,Unknown,Pakistan,3/20/2019,2018,TV-14,1 Season,"International TV Shows, TV Dramas"

In [13]:
df_clean.drop(columns="show_id").duplicated().sum()

np.int64(3)

In [14]:
dup_titles[["show_id", "title", "duration", "listed_in"]]

     show_id   title  duration                             listed_in
2925   s3963  15-Aug   124 min  Comedies, Dramas, Independent Movies
4261   s5967  15-Aug   124 min  Comedies, Dramas, Independent Movies
3285   s4523  22-Jul   144 min                     Dramas, Thrillers
4260   s5966  22-Jul   144 min                     Dramas, Thrillers
393    s3997   9-Feb  1 Season     International TV Shows, TV Dramas
537    s5965   9-Feb  1 Season     International TV Shows, TV Dramas

In [16]:
cols_to_compare = df_clean.columns.drop("show_id")
removed_duplicates = df_clean[df_clean.duplicated(subset=cols_to_compare, keep="first")]

In [17]:
df_clean = df_clean.drop_duplicates(subset=cols_to_compare, keep="first").reset_index(drop=True)

In [18]:
print(df_clean.shape)
print(df_clean.drop(columns="show_id").duplicated().sum())
print(df_clean["show_id"].is_unique)
removed_duplicates[["show_id", "title"]]

(8787, 10)
0
True

     show_id   title
537    s5965   9-Feb
4260   s5966  22-Jul
4261   s5967  15-Aug

In [19]:
date_pattern = r"^\d{1,2}-[A-Za-z]{3}$|^[A-Za-z]{3}-\d{1,2}$"
date_like = df_clean[df_clean["title"].str.match(date_pattern)]
print(len(date_like))

5

In [20]:
date_like[["show_id", "title", "type", "release_year", "director"]]

     show_id   title     type  release_year            director
393    s3997   9-Feb  TV Show          2018             Unknown
2924   s3963  15-Aug    Movie          2019  Swapnaneel Jayakar
3284   s4523  22-Jul    Movie          2018     Paul Greengrass
3743   s5199  SPF-18    Movie          2017         Alex Israel
4258   s5964   1-Oct    Movie          2014      Kunle Afolayan

### Decision: possibly auto-converted titles
Found 5 titles matching a date-like pattern: 9-Feb, 15-Aug, 22-Jul, SPF-18, 1-Oct.
SPF-18 looks like a genuine title (false positive). The other 4 were probably
converted from names such as "22 July" by spreadsheet software. The original
names cannot be recovered from the file alone, so titles were left unchanged and
the issue is documented as a limitation. Impact: 4 of 8,787 rows (about 0.05%).

In [21]:
print(df_clean.shape)
print(df_clean["title"].isin(["9-Feb", "15-Aug", "22-Jul", "SPF-18", "1-Oct"]).sum())

(8787, 10)
5

In [22]:
df_clean["date_added"].str.match(r"^\d{1,2}/\d{1,2}/\d{4}$").value_counts()

date_added
True    8787
Name: count, dtype: int64

In [23]:
parts = df_clean["date_added"].str.split("/", expand=True).astype(int)
print(parts[0].max(), parts[1].max())

12 31

In [24]:
df_clean["duration"].str.split(" ").str[1].value_counts()
pd.crosstab(df_clean["type"], df_clean["duration"].str.split(" ").str[1])

duration  Season  Seasons   min
type
Movie          0        0  6124
TV Show     1790      873     0

In [25]:
df_clean["date_added"] = pd.to_datetime(df_clean["date_added"], format="%m/%d/%Y")

In [26]:
df_clean["duration_value"] = df_clean["duration"].str.split(" ").str[0].astype(int)
df_clean["duration_unit"] = df_clean["duration"].str.split(" ").str[1].replace("Seasons", "Season")

In [27]:
print(df_clean[["date_added", "duration_value"]].dtypes)
print(df_clean["date_added"].min(), df_clean["date_added"].max())
print(df_clean.groupby("duration_unit")["duration_value"].agg(["count", "min", "max"]))
print(df_clean.shape)

date_added        datetime64[us]
duration_value             int64
dtype: object
2008-01-01 00:00:00 2021-09-25 00:00:00
               count  min  max
duration_unit
Season          2663    1   17
min             6124    3  312
(8787, 12)

In [28]:
year_added = df_clean["date_added"].dt.year
early = df_clean[year_added < df_clean["release_year"]]
print(len(early))
print((year_added - df_clean["release_year"]).describe())
early[["title", "type", "release_year", "date_added"]].head(10)

14
count    8787.000000
mean        4.691931
std         8.791157
min        -3.000000
25%         0.000000
50%         1.000000
75%         5.000000
max        93.000000
dtype: float64

                           title     type  release_year date_added
3868  Hans Teeuwen: Real Rancour    Movie          2018 2017-07-01
5135                    Incoming    Movie          2019 2018-10-26
5175                 Jack Taylor  TV Show          2016 2013-03-31
6945                       Hilda  TV Show          2021 2020-12-14
6989                Polly Pocket  TV Show          2021 2020-11-15
7352               Love Is Blind  TV Show          2021 2020-02-13
7433                Fuller House  TV Show          2020 2019-12-06
7481          Maradona in Mexico  TV Show          2020 2019-11-13
7514             BoJack Horseman  TV Show          2020 2019-10-25
7534            The Hook Up Plan  TV Show          2020 2019-10-11

In [29]:
print(early["type"].value_counts())
early[["show_id", "title", "type", "release_year", "date_added"]]

type
TV Show    12
Movie       2
Name: count, dtype: int64

     show_id                       title     type  release_year date_added
3868   s5395  Hans Teeuwen: Real Rancour    Movie          2018 2017-07-01
5135   s7064                    Incoming    Movie          2019 2018-10-26
5175   s7113                 Jack Taylor  TV Show          2016 2013-03-31
6945   s1552                       Hilda  TV Show          2021 2020-12-14
6989   s1697                Polly Pocket  TV Show          2021 2020-11-15
7352   s2921               Love Is Blind  TV Show          2021 2020-02-13
7433   s3169                Fuller House  TV Show          2020 2019-12-06
7481   s3288          Maradona in Mexico  TV Show          2020 2019-11-13
7514   s3370             BoJack Horseman  TV Show          2020 2019-10-25
7534   s3434            The Hook Up Plan  TV Show          2020 2019-10-11
7993   s4845   Unbreakable Kimmy Schmidt  TV Show          2019 2018-05-30
7994   s4846        Arrested Development  TV Show          2019 2018-05-29
8220   s5659                      Sense8  TV Show          2018 2016-12-23
8232   s5678                 Tokyo Trial  TV Show          2017 2016-12-13

In [30]:
df_clean["added_before_release"] = year_added < df_clean["release_year"]
print(df_clean["added_before_release"].sum())
print(df_clean.shape)

14
(8787, 13)